name: Typesense crawler for prod

on:
    push:
        branches:
            - stage

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # environment: stage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3   # You MUST checkout your repository first!

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          host: ${{ secrets.TYPESENSE_HOST }}
          port: 443
          protocol: https
          config: config.json

          # run: |
          #     cat config.json
          #     docker run -it --env-file=.env -e "CONFIG=$(cat config.json | jq -r tostring)" typesense/docsearch-scraper:0.9.1